### ISSUE TITLE
创建获取验证码服务失败

### ISSUE THREAD

**Issue by Jhon714-cooler** [CleverBamboo/renting#3]
![image](https://user-images.githubusercontent.com/51886349/160530191-08e850e7-efdf-4f51-b0a6-f2d4a31af755.png)
GetImageCd/ main.go
`	pb.RegisterGetCaptchaHandler(service.Server(), new(handler.GetCaptcha))
`
报错
_cannot use service.Server() (value of type "github.com/micro/go-micro/server".Server) as "github.com/micro/micro/v3/service/server".Server value in argument to pb.RegisterGetCaptchaHandler: wrong type for method Handle (have func(github.com/micro/go-micro/server.Handler) error, want func(github.com/micro/micro/v3/service/server.Handler) error)compiler[InvalidIfaceAssign](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal?utm_source%3Dgopls#InvalidIfaceAssign)_

**Comment by Bamboo742** [comment]
按报错提示解决问题就行


| |
Alfred
|
|
***@***.***
|
在2022年3月29日 ***@***.***> 写道：


GetImageCd/ main.go
pb.RegisterGetCaptchaHandler(service.Server(), new(handler.GetCaptcha))
报错
cannot use service.Server() (value of type "github.com/micro/go-micro/server".Server) as "github.com/micro/micro/v3/service/server".Server value in argument to pb.RegisterGetCaptchaHandler: wrong type for method Handle (have func(github.com/micro/go-micro/server.Handler) error, want func(github.com/micro/micro/v3/service/server.Handler) error)compilerInvalidIfaceAssign
